name: Brett's Personal Site
email: kaezontpa@gmail.com
description: Home to my musings, collections, and experiments.
url: https://bcost.site
author: Brett Costabile

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "old-site/"]
timezone: America/Detroit
collections:
- ascii_art
plugins:
- jekyll-feed